### ISSUE TITLE
Problem with bag of words

### ISSUE THREAD

**Issue by sensureStefano** [johannfaouzi/pyts#167]
#### Description
I tried using bow by first taking the example given here: [Link](https://pyts.readthedocs.io/en/latest/auto_examples/bag_of_words/plot_bow.html#sphx-glr-auto-examples-bag-of-words-plot-bow-py). With it, all the code works fine. I took the example as below:
[Link_2](https://pyts.readthedocs.io/en/latest/generated/pyts.bag_of_words.BagOfWords.html#pyts.bag_of_words.BagOfWords)

and I get an error when I run bow.transform(X) as below:
`Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\middleware\proxy_fix.py", line 183, in __call__
    return self.app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_restx\api.py", line 671, in error_router
    return original_handler(f)
           ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_restx\api.py", line 669, in error_router
    return self.handle_error(e)
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_restx\api.py", line 671, in error_router
    return original_handler(f)
           ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_restx\api.py", line 669, in error_router
    return self.handle_error(e)
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_restx\api.py", line 402, in wrapper
    resp = resource(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_restx\resource.py", line 41, in dispatch_request
    resp = meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Gatherer\SenPy\app\analysis.py", line 871, in post
    df_Hysteria=calcPattern(df_feat,bodyP['meanVal'])#calcHysteriaFeat(df_feat, bodyP['meanVal'])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Gatherer\SenPy\app\analysis.py", line 793, in calcPattern
    bow.transform(X)
  File "c:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\_set_output.py", line 316, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyts\bag_of_words\bow.py", line 302, in transform
    X_window = _windowed_view(
               ^^^^^^^^^^^^^^^
  File "<stringsource>", line 69, in cfunc.to_py.__Pyx_CFunc_893235__29_pydevd_sys_monitoring_cython_object__lParen__etc_to_py_4code_18instruction_offset.wrap
  File "_pydevd_sys_monitoring\\_pydevd_sys_monitoring_cython.pyx", line 1697, in _pydevd_sys_monitoring_cython._start_method_event
  File "_pydevd_sys_monitoring\\_pydevd_sys_monitoring_cython.pyx", line 599, in _pydevd_sys_monitoring_cython._get_func_code_info
AssertionError: <code object transform at 0x000001DED9D2B070, file "c:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyts\bag_of_words\bow.py", line 275> != <code object _windowed_view at 0x000001DEDB7135F0, file "c:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyts\utils\utils.py", line 103>`

The same problem is present when i use on my data, that are float numbers in a array of 1 sample (for example taken from X=df_gd.loc[:,"Value"].values.reshape(1,-1))

**Comment by johannfaouzi** [comment]
I'm not sure that the problem comes from `pyts`. If you look at the traceback, you can see that there are a lot of calls (mostly from `flask`). I'm not familiar with the error that is occurring, but it seems like two objects are different:
```
AssertionError: 
<code object transform at 0x000001DED9D2B070, file "c:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyts\bag_of_words\bow.py", line 275>
 !=
<code object _windowed_view at 0x000001DEDB7135F0, file "c:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyts\utils\utils.py", line 103>
```

Could you please try to reproduce this error without using an application (like flask), but just the library itself?

**Comment by sensureStefano** [comment]
Probably yes... i see that without flask it works. Also i tried to take your code and insert in my code and, after remove the @njit, it works... Thanks
