### ISSUE TITLE
ImportError: cannot import name 'PowerTransformer'

### ISSUE THREAD

**Issue by bingyue0610** [johannfaouzi/pyts#26]
#### Steps/Code to Reproduce

```python
<< 
from pyts.image import mtf

Traceback (most recent call last):
  File "C:\Users\BBD\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-33-02178b70bcc1>", line 1, in <module>
    from pyts.image import mtf
  File "E:\pycharm\PyCharm 2018.3.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\BBD\Anaconda3\lib\site-packages\pyts\image\__init__.py", line 6, in <module>
    from .gaf import GramianAngularField
  File "E:\pycharm\PyCharm 2018.3.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\BBD\Anaconda3\lib\site-packages\pyts\image\gaf.py", line 8, in <module>
    from ..approximation import PiecewiseAggregateApproximation
  File "E:\pycharm\PyCharm 2018.3.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\BBD\Anaconda3\lib\site-packages\pyts\approximation\__init__.py", line 4, in <module>
    from .sax import SymbolicAggregateApproximation
  File "E:\pycharm\PyCharm 2018.3.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\BBD\Anaconda3\lib\site-packages\pyts\approximation\sax.py", line 6, in <module>
    from ..preprocessing import KBinsDiscretizer
  File "E:\pycharm\PyCharm 2018.3.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\BBD\Anaconda3\lib\site-packages\pyts\preprocessing\__init__.py", line 4, in <module>
    from .transformer import PowerTransformer, QuantileTransformer
  File "E:\pycharm\PyCharm 2018.3.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\BBD\Anaconda3\lib\site-packages\pyts\preprocessing\transformer.py", line 4, in <module>
    from sklearn.preprocessing import PowerTransformer as SklearnPowerTransformer
ImportError: cannot import name 'PowerTransformer'


>>
```

**Comment by bingyue0610** [comment]
It has been resolved! Thank you!

**Comment by Erwachen6** [comment]
Can I know how you solved it? I'm also getting this error now.

**Comment by Erwachen6** [comment]
> It has been resolved! Thank you!
Can I know how you solved it? I'm also getting this error now.

**Comment by johannfaouzi** [comment]
Hi,

`scikit-learn` is a dependency of the package and is installed when you install `pyts`. [sklearn.preprocessing.PowerTransformer](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.PowerTransformer.html) has been added in `scikit-learn==0.20` and `pyts` requires `scikit-learn>=0.22`, so it should be available.

Can you please give the versions of the these packages?
```python
import pyts; print("pyts", pyts.__version__)
import sklearn; print("scikit-learn", sklearn.__version__)
```

**Comment by Erwachen6** [comment]
Thank you! I have resolve it!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "johannfaouzi/pyts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月5日(星期一) 下午5:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [johannfaouzi/pyts] ImportError: cannot import name 'PowerTransformer' (#26)





 
Hi,
 
scikit-learn is a dependency of the package and is installed when you install pyts. sklearn.preprocessing.PowerTransformer has been added in scikit-learn==0.20 and pyts requires scikit-learn&gt;=0.22, so it should be available.
 
Can you please give the versions of the these packages?
 import pyts; print("pyts", pyts.__version__) import sklearn; print("scikit-learn", sklearn.__version__)
